# Site settings
title: Github notifier
email:
description: github desktop notifications in macOS
baseurl: "https://sargsyan.github.io/github-notifier/" # the subpath of your site, e.g. /blog/
url: # the base hostname & protocol for your site

twitter_username:
github_username:

# Build settings
markdown: kramdown

plugins:
  - jekyll-seo-tag
