# Site settings
title: github-notifier
email:
description: Github desktop notifications in macOS
baseurl: "/github-notifier/" # the subpath of your site, e.g. /blog/
url: "https://sargsyan.github.io/" # the base hostname & protocol for your site

twitter_username:
github_username:

# Build settings
markdown: kramdown

plugins:
  - jekyll-seo-tag
